include(FindPackageHandleStandardArgs)
if(NOT TARGET GMP)
    find_library(GMP_LIBRARY gmp)
    find_file(GMP_HEADERS gmp.h)
    find_file(GMP_CPP_HEADERS gmpxx.h)

    if(GMP_LIBRARY)
        if(GMP_LIBRARY MATCHES ".a")
            add_library(GMP STATIC IMPORTED ${GMP_LIBRARY})
            add_library(GMP_CPP STATIC IMPORTED ${GMP_LIBRARY})
        else()
            add_library(GMP SHARED IMPORTED ${GMP_LIBRARY})
            add_library(GMP_CPP SHARED IMPORTED ${GMP_LIBRARY})
        endif()
        if(GMP_HEADERS)
            get_filename_component(GMP_HEADERS_DIR "${GMP_HEADERS}" DIRECTORY)
            target_include_directories(GMP INTERFACE "${GMP_HEADERS_DIR}")
        endif()
        if(GMP_CPP_HEADERS)
            get_filename_component(GMP_CPP_HEADERS_DIR "${GMP_CPP_HEADERS}" DIRECTORY)
            target_include_directories(GMP_CPP INTERFACE "${GMP_CPP_HEADERS_DIR}")
        endif()
    endif()
    find_package_handle_standard_args(GMP DEFAULT_MSG GMP_LIBRARY GMP_HEADERS GMP_CPP_HEADERS_DIR)
endif()